openapi: 3.0.0
info:
  title: Guide Brands API
  version: "2.0"
paths:
  /guide/brands:
    get:
      summary: Get brand list
      description: |
        Gets the brands offered by the account.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BrandsListResponse"
  /guide/brands/{brand_id}:
    parameters:
      - name: brand_id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get brand
      description: |
        Gets information about a single brand, identified by it's ID.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BrandsListItem"
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: "components_common.yaml#/components/schemas/ErrorListResponse"
components:
  schemas:
    BrandsListResponse:
      type: object
      properties:
        brands:
          type: array
          items:
            $ref: "#/components/schemas/BrandsListItem"
    BrandsListItem:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: The brand ID, most often referred to with parameters or properties named `brand_id`.
          example: 12345
        subdomain:
          type: string
          description: The Zendesk brand subdomain.
          example: developer
        help_center_url:
          type: string
          description: The URL to the Help Center of this brand
          example: https://developer.zendesk.com
