openapi: 3.0.0
info:
  title: Help Center API
  description: >
    API for a Help Center provided via the Zendesk Guide and Zendesk Gather
    products.
  version: "2.0"
servers:
  - url: /api/v2
paths:
  /gather/brands:
    get:
      summary: Gets brands with Gather communities activated.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GatherBrandsListingResponse"
  /gather/moderation/{brand_id}/spam:
    parameters:
      - name: brand_id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Gets spam content in the moderation queue
      description: |
        Gets content that has been marked as spam.
      tags:
       - Moderation
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModerationItemsResponse"
  /gather/moderation/{brand_id}/user_content:
    parameters:
      - name: brand_id
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
       - Moderation
      summary: Get user content in the moderation queue
      description: |
        Gets content that has been placed in the moderation queue
        and is therefore not yet public.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModerationItemsResponse"
  /gather/moderation/{brand_id}/content_items/{content_item_id}:
    parameters:
      - name: brand_id
        in: path
        required: true
        schema:
          type: string
      - name: content_item_id
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
       - Moderation
      summary: Get moderated item
      description: |
        Gets information about an individual item that has been placed under moderation.
      responses:
        200:
          description: Success
  /gather/moderation/{brand_id}/content_items/{content_item_id}/approve:
    parameters:
      - name: brand_id
        in: path
        required: true
        schema:
          type: string
      - name: content_item_id
        in: path
        required: true
        schema:
          type: string
    post:
      tags:
       - Moderation
      summary: Approve content
      description: |
        Approves an item that has been placed in the moderation queue.
        The content will be published into the containing community topic, post or article.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GatherModerationApproveContentRequest"
      responses:
        200:
          description: Success
  /gather/moderation/{brand_id}/content_items/{content_item_id}/reject:
    parameters:
      - name: brand_id
        in: path
        required: true
        schema:
          type: string
      - name: content_item_id
        in: path
        required: true
        schema:
          type: string
    post:
      tags:
       - Moderation
      summary: Reject content
      description: |
        Approves an item that has been placed in the moderation queue.
        The content will be deleted and no longer available to anyone.
      responses:
        200:
          description: Success
components:
  schemas:
    GatherBrandsListingResponse:
      type: object
      properties:
        brands:
          type: array
          items:
            $ref: "#/components/schemas/GatherBrandsListingResponseItem"
    GatherBrandsListingResponseItem:
      type: object
      properties:
        id:
          description: The brand ID
          type: string
          example: z3n-showcase
        name:
          description: The brand name
          type: string
          example: Shoe La La
        help_center_url:
          description: URL of the brand's Help Center
          type: string
          example: https://z3n-showcase.zendesk.com
    GatherModerationApproveContentRequest:
      type: object
    ModerationItemsResponse:
      type: object
