openapi: '3.0.2'
info:
  title: Kasper's API
  version: '1.0'
servers:
  - url: https://github.com/kaspersorensen
paths:
  /test:
    get:
      summary: This is an example
      description: |
        Here's a `test` link for *Guide REST*.

        It can be multiple lines.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Foo"
components:
    schemas:
      Foo:
        type: object
        properties:
          greeting:
            type: string
            example: Hello
